apiVersion: apps/v1
kind: Deployment
metadata:
  name: wana-frontend-deployment
  labels:
    app: wana-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wana-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wana-frontend
    spec:
      containers:
        - name: wana-frontend
          image: eu.gcr.io/tea-project-211819/simonsinding/wana-frontend
          ports:
            - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: wana-frontend-service
spec:
  type: NodePort
  selector:
    app: wana-frontend
  ports:
    - name: frontend-port
      protocol: TCP
      port: 80
      targetPort: 5000
